/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAO;

import conexao.Games;

/**
 *
 * @author aluno
 */
public class CadGame extends javax.swing.JFrame {

    /**
     * Creates new form CadGame
     *
     */
    private String caminhoImagemSelecionada;

    public CadGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Statu = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdo_QueroJogar = new javax.swing.JRadioButton();
        rdo_Jogando = new javax.swing.JRadioButton();
        rdo_Zerado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Plataforma = new javax.swing.JTextField();
        JLabel4 = new javax.swing.JLabel();
        txt_Genero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        check_Multi = new javax.swing.JCheckBox();
        spn_Ano = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        lbl_Imagem = new javax.swing.JLabel();
        btn_Imagem = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        txt_Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Nome.setPreferredSize(new java.awt.Dimension(10, 30));
        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Status:");

        grupo_Statu.add(rdo_QueroJogar);
        rdo_QueroJogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_QueroJogar.setText("Quero Jogar");

        grupo_Statu.add(rdo_Jogando);
        rdo_Jogando.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_Jogando.setLabel("Jogando");

        grupo_Statu.add(rdo_Zerado);
        rdo_Zerado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_Zerado.setText("Zerado");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Plataforma:");

        txt_Plataforma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Plataforma.setPreferredSize(new java.awt.Dimension(10, 30));

        JLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabel4.setText("Gênero:");

        txt_Genero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Genero.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Multiplayer:");

        check_Multi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check_Multi.setText("SIM");

        spn_Ano.setModel(new javax.swing.SpinnerNumberModel(2026, 1970, 2030, 1));
        spn_Ano.setPreferredSize(new java.awt.Dimension(93, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ano de Lançamento");

        lbl_Imagem.setBackground(new java.awt.Color(182, 181, 181));
        lbl_Imagem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Imagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_Imagem.setOpaque(true);

        btn_Imagem.setText("Selecionar Imagem");
        btn_Imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImagemActionPerformed(evt);
            }
        });

        btn_Salvar.setText("SALVAR");
        btn_Salvar.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Plataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_QueroJogar)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_Jogando)))
                        .addGap(18, 18, 18)
                        .addComponent(rdo_Zerado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(check_Multi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(spn_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Imagem))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Imagem, lbl_Imagem});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdo_QueroJogar)
                            .addComponent(rdo_Jogando)
                            .addComponent(rdo_Zerado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_Imagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_Multi)
                    .addComponent(btn_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spn_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btn_ImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImagemActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imagens", "jpg", "jpeg", "png"));

        int resultado = chooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File arquivo = chooser.getSelectedFile();
            caminhoImagemSelecionada = arquivo.getAbsolutePath();

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(caminhoImagemSelecionada);
            java.awt.Image imagemRedimensionada = icon.getImage().getScaledInstance(
                    lbl_Imagem.getWidth(), lbl_Imagem.getHeight(), java.awt.Image.SCALE_SMOOTH);
            lbl_Imagem.setIcon(new javax.swing.ImageIcon(imagemRedimensionada));
        }
    }//GEN-LAST:event_btn_ImagemActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed

        Games g = new Games();
        g.setNome(txt_Nome.getText());
        g.setPlataforma(txt_Plataforma.getText());
        g.setGenero(txt_Genero.getText());
        g.setMultiplayer(check_Multi.isSelected());
        g.setAnoLancamento((int) spn_Ano.getValue());
        if (caminhoImagemSelecionada == null) {
            g.setCaminhoImagem(""); // Se não houver imagem, envia um texto vazio
        } else {
            g.setCaminhoImagem(caminhoImagemSelecionada); // Se houver, envia o caminho
        }

        if (rdo_QueroJogar.isSelected()) {
            g.setStatus("Quero Jogar");
        } else if (rdo_Jogando.isSelected()) {
            g.setStatus("Jogando");
        } else if (rdo_Zerado.isSelected()) {
            g.setStatus("Zerado");
        } else {
            g.setStatus("Não definido");
        }

        GamesDAO gDAO = new GamesDAO();
        gDAO.inserir(g);
        limparFormulario();
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void limparFormulario() {
        txt_Nome.setText("");
        grupo_Statu.clearSelection();
        txt_Plataforma.setText("");
        txt_Genero.setText("");
        check_Multi.setSelected(false);
        spn_Ano.setValue(2026);
        lbl_Imagem.setIcon(null);
        caminhoImagemSelecionada = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton btn_Imagem;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JCheckBox check_Multi;
    private javax.swing.ButtonGroup grupo_Statu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_Imagem;
    private javax.swing.JRadioButton rdo_Jogando;
    private javax.swing.JRadioButton rdo_QueroJogar;
    private javax.swing.JRadioButton rdo_Zerado;
    private javax.swing.JSpinner spn_Ano;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Plataforma;
    // End of variables declaration//GEN-END:variables
}
