/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAO;

import conexao.Games;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class EditGames extends javax.swing.JFrame {

    /**
     * Creates new form EditGames
     */
    private String caminhoImagemSelecionada;

    public EditGames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void limparFormulario() {
        txt_Nome.setText("");
        grupo_Statu.clearSelection();
        txt_Plataforma.setText("");
        txt_Genero.setText("");
        check_Multi.setSelected(false);
        spn_Ano.setValue(2026);
        lbl_Imagem.setIcon(null);
        caminhoImagemSelecionada = null;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Statu = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        txt_Plataforma = new javax.swing.JTextField();
        JLabel4 = new javax.swing.JLabel();
        txt_Genero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        check_Multi = new javax.swing.JCheckBox();
        txt_Nome = new javax.swing.JTextField();
        spn_Ano = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdo_QueroJogar = new javax.swing.JRadioButton();
        lbl_Imagem = new javax.swing.JLabel();
        rdo_Jogando = new javax.swing.JRadioButton();
        btn_Imagem = new javax.swing.JButton();
        rdo_Zerado = new javax.swing.JRadioButton();
        btn_Salvar = new javax.swing.JButton();
        txt_IdGame = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Plataforma:");

        txt_Plataforma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Plataforma.setPreferredSize(new java.awt.Dimension(10, 30));

        JLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLabel4.setText("Gênero:");

        txt_Genero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Genero.setPreferredSize(new java.awt.Dimension(10, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Multiplayer:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        check_Multi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        check_Multi.setText("SIM");

        txt_Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Nome.setPreferredSize(new java.awt.Dimension(10, 30));
        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        spn_Ano.setModel(new javax.swing.SpinnerNumberModel(2026, 1970, 2030, 1));
        spn_Ano.setPreferredSize(new java.awt.Dimension(93, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Status:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ano de Lançamento");

        grupo_Statu.add(rdo_QueroJogar);
        rdo_QueroJogar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_QueroJogar.setText("Quero Jogar");

        lbl_Imagem.setBackground(new java.awt.Color(182, 181, 181));
        lbl_Imagem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Imagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_Imagem.setOpaque(true);

        grupo_Statu.add(rdo_Jogando);
        rdo_Jogando.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_Jogando.setLabel("Jogando");

        btn_Imagem.setText("Selecionar Imagem");
        btn_Imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImagemActionPerformed(evt);
            }
        });

        grupo_Statu.add(rdo_Zerado);
        rdo_Zerado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdo_Zerado.setText("Zerado");

        btn_Salvar.setText("SALVAR");
        btn_Salvar.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        txt_IdGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_IdGame.setPreferredSize(new java.awt.Dimension(10, 30));
        txt_IdGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdGameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Id:");

        btn_Pesquisar.setText("Pesquisar");
        btn_Pesquisar.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        btn_Excluir.setText("EXCLUIR");
        btn_Excluir.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Plataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_QueroJogar)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_Jogando)))
                                .addGap(18, 18, 18)
                                .addComponent(rdo_Zerado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(check_Multi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(spn_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Imagem))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_IdGame, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdo_QueroJogar)
                            .addComponent(rdo_Jogando)
                            .addComponent(rdo_Zerado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_Imagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_Multi)
                    .addComponent(btn_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spn_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btn_ImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImagemActionPerformed

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imagens", "jpg", "jpeg", "png"));

        int resultado = chooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File arquivo = chooser.getSelectedFile();
            caminhoImagemSelecionada = arquivo.getAbsolutePath();

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(caminhoImagemSelecionada);
            java.awt.Image img = icon.getImage();

            // Lê as dimensões da JLabel
            int largura = lbl_Imagem.getWidth();
            int altura = lbl_Imagem.getHeight();

            // Só redimensiona se a largura e altura forem válidas (maiores que zero)
            if (largura > 0 && altura > 0 && img != null) {
                java.awt.Image imagemRedimensionada = img.getScaledInstance(
                        largura, altura, java.awt.Image.SCALE_SMOOTH);
                lbl_Imagem.setIcon(new javax.swing.ImageIcon(imagemRedimensionada));
            } else {
                // Se as dimensões derem erro, carrega a imagem no tamanho original
                lbl_Imagem.setIcon(icon);
            }
        }

    }//GEN-LAST:event_btn_ImagemActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        Games g = new Games();
        g.setId(Integer.parseInt(txt_IdGame.getText()));
        g.setNome(txt_Nome.getText());
        g.setPlataforma(txt_Plataforma.getText());
        g.setGenero(txt_Genero.getText());
        g.setMultiplayer(check_Multi.isSelected());
        g.setAnoLancamento((int) spn_Ano.getValue());
        if (caminhoImagemSelecionada == null) {
            g.setCaminhoImagem(""); // Se não houver imagem, envia um texto vazio
        } else {
            g.setCaminhoImagem(caminhoImagemSelecionada); // Se houver, envia o caminho
        }

        if (rdo_QueroJogar.isSelected()) {
            g.setStatus("Quero Jogar");
        } else if (rdo_Jogando.isSelected()) {
            g.setStatus("Jogando");
        } else if (rdo_Zerado.isSelected()) {
            g.setStatus("Zerado");
        } else {
            g.setStatus("Não definido");
        }

        GamesDAO gDAO = new GamesDAO();
        gDAO.editar(g);
        limparFormulario();

    }//GEN-LAST:event_btn_SalvarActionPerformed


    private void txt_IdGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdGameActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed

        if (txt_IdGame.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido antes de pesquisar.");
            return; // O 'return' faz com que o código pare aqui e não tente pesquisar
        }

        int idGame = Integer.parseInt(txt_IdGame.getText());
        GamesDAO gDAO = new GamesDAO();

        Games g = gDAO.getGames(idGame);

        if (g == null) {
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Jogo não encontrado!");
        } else {
            txt_IdGame.setText(String.valueOf(g.getId()));
            txt_Nome.setText(g.getNome());
            if ("Quero Jogar".equals(g.getStatus())) {
                rdo_QueroJogar.setSelected(true);
            } else if ("Jogando".equals(g.getStatus())) {
                rdo_Jogando.setSelected(true);
            } else if ("Zerado".equals(g.getStatus())) {
                rdo_Zerado.setSelected(true);
            } else {
                grupo_Statu.clearSelection();
            }
            txt_Plataforma.setText(g.getPlataforma());
            txt_Genero.setText(g.getGenero());
            check_Multi.setSelected(g.isMultiplayer());
            spn_Ano.setValue(g.getAnoLancamento());

            String caminho = g.getCaminhoImagem();

            if (caminho != null && !caminho.trim().isEmpty()) {
                java.io.File ficheiro = new java.io.File(caminho);

                // Verifica se o ficheiro ainda existe no computador
                if (ficheiro.exists()) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(caminho);
                    java.awt.Image img = icon.getImage();

                    int largura = lbl_Imagem.getWidth();
                    int altura = lbl_Imagem.getHeight();

                    // Se a largura e altura já estiverem definidas, redimensiona a imagem
                    if (largura > 0 && altura > 0) {
                        java.awt.Image imgRedimensionada = img.getScaledInstance(
                                largura, altura, java.awt.Image.SCALE_SMOOTH);
                        lbl_Imagem.setIcon(new javax.swing.ImageIcon(imgRedimensionada));
                    } else {

                        lbl_Imagem.setIcon(icon);
                    }

                    caminhoImagemSelecionada = caminho;
                } else {
                    lbl_Imagem.setIcon(null);
                    caminhoImagemSelecionada = null;
                }
            } else {

                lbl_Imagem.setIcon(null);
                caminhoImagemSelecionada = null;
            }
        }

    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        if (txt_IdGame.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduza um ID antes de excluir.");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            GamesDAO gDAO = new GamesDAO();
            gDAO.excluir(Integer.parseInt(txt_IdGame.getText()));
            limparFormulario();

        }


    }//GEN-LAST:event_btn_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditGames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel4;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Imagem;
    private javax.swing.JButton btn_Pesquisar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JCheckBox check_Multi;
    private javax.swing.ButtonGroup grupo_Statu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_Imagem;
    private javax.swing.JRadioButton rdo_Jogando;
    private javax.swing.JRadioButton rdo_QueroJogar;
    private javax.swing.JRadioButton rdo_Zerado;
    private javax.swing.JSpinner spn_Ano;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_IdGame;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Plataforma;
    // End of variables declaration//GEN-END:variables
}
